name: Release Build
on:
    push:
        tags:
            - "v*"
jobs:
    Build:
        name: Build/Sign APK
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build APKs
              id: build
              run: bash ./gradlew assembleRelease
            - name: Sign APKs
              id: sign_apk
              uses: r0adkll/sign-android-release@v1
              with:
                  releaseDirectory: app/build/outputs/apk/release
                  signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
                  alias: ${{ secrets.ANDROID_KEY_ALIAS }}
                  keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
                  keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
            - uses: jungwinter/split@v1
              id: signed_files
              with:
                  msg: ${{ steps.sign_app.signedReleaseFiles }}
                  separator: ":"
            - name: Upload APKs
              uses: actions/upload-artifact@v2
              with:
                  name: signed-apks
                  path: |
                      ${{ steps.signed_files.outputs._0 }}
                      ${{ steps.signed_files.outputs._1 }}
                      ${{ steps.signed_files.outputs._2 }}
                      ${{ steps.signed_files.outputs._3 }}
                      ${{ steps.signed_files.outputs._4 }}
                      ${{ steps.signed_files.outputs._5 }}
            - name: Release APKs
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "${{ github.ref }}"
                  prerelease: true
                  files: |
                      ${{ steps.signed_files.outputs._0 }}
                      ${{ steps.signed_files.outputs._1 }}
                      ${{ steps.signed_files.outputs._2 }}
                      ${{ steps.signed_files.outputs._3 }}
                      ${{ steps.signed_files.outputs._4 }}
                      ${{ steps.signed_files.outputs._5 }}
