name: Release Build
on:
  push:
    tags:
      - 'v*'
jobs:
  Build:
    name: Build/Sign APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build APKs
        id: build
        run: bash ./gradlew assembleRelease
      - name: Sign APKs
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Release APKs
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            ${{ steps.sign_apk.signedReleaseFile0 }}
            ${{ steps.sign_apk.signedReleaseFile1 }}
            ${{ steps.sign_apk.signedReleaseFile2 }}
            ${{ steps.sign_apk.signedReleaseFile3 }}
            ${{ steps.sign_apk.signedReleaseFile4 }}
            ${{ steps.sign_apk.signedReleaseFile5 }}
